### ISSUE TITLE
Encrypt function returning Byte Array instead of string

### ISSUE THREAD

**Issue by RSpicer** [awslabs/aws-encryption-sdk-python#6]
Hi there! I'm new to using this library, so forgive any stupid questions :). When I call the encrypt function, it returns a byte array... although, in the documentation, it says it's supposed to return a string. My implementation relies on the ciphertext being returned as a string - if I'm missing something, and it can't be, is there an encoding for the byte array I can use to convert it in to a string?

Thanks for your help!

**Comment by mattsb42-aws** [comment]
Hmm, the docs should all indicate a bytes return value; I'll check on that and fix the points I missed.

It is intentional that it is returning bytes rather than a string, as it it returning the raw encrypted message, which will almost always include non-ascii characters.  If you need a string we generally recommend base64 encoding the bytes.

**Comment by RSpicer** [comment]
That works - cheers mate! Thanks much for the quick answer!
